-- ========================================================
-- FITCORE GYM MANAGEMENT SYSTEM - DA2 DATABASE SCHEMA
-- Topic: Gym Management & Equipment Database
-- Compatible with: Oracle Database 19c/21c/XE and MySQL 8.0
-- ========================================================

-- Drop existing tables in reverse dependency order (if re-running)
-- DROP TABLE PAYMENT CASCADE CONSTRAINTS;
-- DROP TABLE MAINTENANCE CASCADE CONSTRAINTS;
-- DROP TABLE EQUIPMENT_USAGE CASCADE CONSTRAINTS;
-- DROP TABLE EQUIPMENT CASCADE CONSTRAINTS;
-- DROP TABLE TRAINER CASCADE CONSTRAINTS;
-- DROP TABLE MEMBER CASCADE CONSTRAINTS;

-- 1. MEMBER TABLE
-- Stores registered gym members, demographic data, and membership tier.
CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR(10) PRIMARY KEY,
    MEMBER_NAME VARCHAR(60) NOT NULL,
    AGE INT CHECK (AGE >= 14),
    GENDER VARCHAR(10) CHECK (GENDER IN ('Male', 'Female', 'Other')),
    PHONE VARCHAR(15) UNIQUE NOT NULL,
    MEMBERSHIP_TYPE VARCHAR(20) NOT NULL CHECK (MEMBERSHIP_TYPE IN ('Basic', 'Standard', 'Premium')),
    JOIN_DATE DATE DEFAULT CURRENT_DATE
);

-- 2. TRAINER TABLE
-- Stores certified gym trainers, contact details, specializations and experience.
CREATE TABLE TRAINER (
    TRAINER_ID VARCHAR(10) PRIMARY KEY,
    TRAINER_NAME VARCHAR(60) NOT NULL,
    PHONE VARCHAR(15) UNIQUE NOT NULL,
    SPECIALIZATION VARCHAR(50) NOT NULL,
    EXPERIENCE VARCHAR(30) NOT NULL
);

-- 3. EQUIPMENT TABLE
-- Stores gym machinery, purchase information, condition and operating status.
CREATE TABLE EQUIPMENT (
    EQUIPMENT_ID VARCHAR(10) PRIMARY KEY,
    EQUIPMENT_NAME VARCHAR(60) NOT NULL,
    CATEGORY VARCHAR(30) NOT NULL CHECK (CATEGORY IN ('Cardio', 'Strength', 'Free Weight')),
    BRAND VARCHAR(40) NOT NULL,
    PURCHASE_DATE DATE NOT NULL,
    CONDITION VARCHAR(20) NOT NULL CHECK (CONDITION IN ('Good', 'Fair', 'Poor')),
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('Available', 'Maintenance', 'Unavailable'))
);

-- 4. EQUIPMENT_USAGE TABLE
-- Records member equipment workout sessions supervised by trainers (Relationship 1:M).
CREATE TABLE EQUIPMENT_USAGE (
    USAGE_ID VARCHAR(10) PRIMARY KEY,
    MEMBER_ID VARCHAR(10) NOT NULL,
    EQUIPMENT_ID VARCHAR(10) NOT NULL,
    TRAINER_ID VARCHAR(10) NOT NULL,
    USAGE_DATE DATE NOT NULL,
    DURATION VARCHAR(30) NOT NULL,
    CONSTRAINT FK_USAGE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USAGE_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(EQUIPMENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USAGE_TRAINER FOREIGN KEY (TRAINER_ID) REFERENCES TRAINER(TRAINER_ID) ON DELETE CASCADE
);

-- 5. MAINTENANCE TABLE
-- Tracks servicing, repairs, parts replacement and technician expenses.
CREATE TABLE MAINTENANCE (
    MAINTENANCE_ID VARCHAR(10) PRIMARY KEY,
    EQUIPMENT_ID VARCHAR(10) NOT NULL,
    MAINTENANCE_DATE DATE NOT NULL,
    TECHNICIAN_NAME VARCHAR(60) NOT NULL,
    COST DECIMAL(10,2) NOT NULL CHECK (COST >= 0),
    REMARKS VARCHAR(150),
    CONSTRAINT FK_MAINTENANCE_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(EQUIPMENT_ID) ON DELETE CASCADE
);

-- 6. PAYMENT TABLE
-- Financial billing records for membership dues, payment mode, and status.
CREATE TABLE PAYMENT (
    PAYMENT_ID VARCHAR(10) PRIMARY KEY,
    MEMBER_ID VARCHAR(10) NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL CHECK (AMOUNT > 0),
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_MODE VARCHAR(20) NOT NULL CHECK (PAYMENT_MODE IN ('UPI', 'Card', 'Cash', 'Net Banking')),
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('Paid', 'Pending', 'Failed')),
    CONSTRAINT FK_PAYMENT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);

-- Create helpful indexes for performance
CREATE INDEX IDX_USAGE_MEMBER ON EQUIPMENT_USAGE(MEMBER_ID);
CREATE INDEX IDX_USAGE_EQUIP ON EQUIPMENT_USAGE(EQUIPMENT_ID);
CREATE INDEX IDX_PAYMENT_STATUS ON PAYMENT(STATUS);
CREATE INDEX IDX_EQUIP_STATUS ON EQUIPMENT(STATUS);
